Remove version-going-backwards
We don't use a package feed for building, so version timestamps can sometimes
cause an error of the form:
    ERROR: u-boot-uenv-1.0-r0 do_packagedata_setscene: QA Issue: Package
    version for package u-boot-uenv-src went backwards which would break
    package feeds (from 0:1.0-r0.11 to 0:1.0-r0.9) [version-going-backwards]

In particular, this can happen when building for multiple MACHINEs in sequence.

This patch removes the check for version-going-backwards.